version: '3'
services:
  service-backend:
    container_name: admotiv-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
      - ./secrets:/secrets
    entrypoint: ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--ssl-keyfile=/secrets/key.pem", "--ssl-certfile=/secrets/cert.pem"]